### ISSUE TITLE
"path must begin with '/' in path ''" when using regex validation

### ISSUE THREAD

**Issue by Lukaesebrot** [fasthttp/router#39]
Hey^^

I use the following line to achieve a regex validation on a path:
`router.GET("/{filepath:^(?!api).*}", frontend.RequestHandler)`

I want that this route only applies if the path does not begin with `api`. My problem is that the program panics:
```
panic: path must begin with '/' in path ''

goroutine 1 [running]:
github.com/fasthttp/router/radix.panicf(...)
        C:/Users/lukas/go/pkg/mod/github.com/fasthttp/router@v1.2.4/radix/utils.go:13
github.com/fasthttp/router/radix.(*Tree).Add(0xc0000a8070, 0xea52fc, 0x0, 0xc0000a8050)
        C:/Users/lukas/go/pkg/mod/github.com/fasthttp/router@v1.2.4/radix/tree.go:24 +0x44a
github.com/fasthttp/router.(*Router).Handle(0xc0000ac000, 0xe9e85a, 0x3, 0xea52fc, 0x18, 0xc0000a8050)
        C:/Users/lukas/go/pkg/mod/github.com/fasthttp/router@v1.2.4/router.go:198 +0x1f3
github.com/fasthttp/router.(*Router).GET(...)
        C:/Users/lukas/go/pkg/mod/github.com/fasthttp/router@v1.2.4/router.go:74
```

**Comment by savsgio** [comment]
Hi @Lukaesebrot,

Thanks for your issue, i've just upload the fix 😉
